# Generated by Django 3.1.14 on 2022-12-28 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_coupon_required_amount_to_use_coupo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='required_amount_to_use_coupo',
            new_name='required_amount_to_use_coupon',
        ),
    ]
